[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dataprep_tools"
version = "0.0.6"
authors = [
    {name="Anjor"}
]
description = "Utils to prepare data for filecoin deals"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
